### ISSUE TITLE
Missed Arduino.h header include

### ISSUE THREAD

**Issue by SNMetamorph** [MrTransistorsChannel/NixdorfVFD#1]
Needed `#include <Arduino.h>` on line 3 for proper working with PlatformIO.
https://github.com/MrTransistorsChannel/NixdorfVFD/blob/5e86c5f1ba1da7b0ab6072635e94692490cfd4bf/src/NixdorfVFD.h#L1-L8

**Comment by MrTransistorsChannel** [comment]
Thanks, fixed in [v1.0.2](https://github.com/MrTransistorsChannel/NixdorfVFD/releases/tag/v1.0.2)
